import 'package:flutter/material.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget1/generated/GeneratedGroup17Widget4.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget1/generated/GeneratedEstimatedTimetoFullChrageWidget1.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget1/generated/GeneratedShapeWidget6.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget1/generated/GeneratedGroup16Widget4.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget1/generated/GeneratedGroup18Widget4.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget1/generated/GeneratedInputWidget15.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget1/generated/GeneratedGroup50Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget1/generated/GeneratedRectangle56Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget1/generated/GeneratedRectangle43Widget4.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget1/generated/GeneratedRectangle55Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget1/generated/GeneratedBibatterychargingWidget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget1/generated/GeneratedEllipse12Widget4.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget1/generated/GeneratedGroup64Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget1/generated/GeneratedGroup48Widget1.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget1/generated/GeneratedSTOPWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget1/generated/GeneratedNotificationWidget6.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget1/generated/GeneratedChargingWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget1/generated/Generated52Widget.dart';

/* Frame Charging Entry
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChargingEntryWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 246, 246, 246),
                ),
              ),
              Positioned(
                left: 349.6666564941406,
                top: 0.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedBibatterychargingWidget3(),
              ),
              Positioned(
                left: -99.0,
                top: -109.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 270.0,
                child: GeneratedShapeWidget6(),
              ),
              Positioned(
                left: 25.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 324.6666564941406,
                height: 16.0,
                child: GeneratedNotificationWidget6(),
              ),
              Positioned(
                left: 16.0,
                top: 184.0,
                right: null,
                bottom: null,
                width: 338.0,
                height: 559.0,
                child: GeneratedInputWidget15(),
              ),
              Positioned(
                left: 121.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 61.0,
                child: GeneratedChargingWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 755.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 83.0,
                child: GeneratedRectangle43Widget4(),
              ),
              Positioned(
                left: 259.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 94.0,
                child: GeneratedEllipse12Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.096;

                  final double height =
                      constraints.maxHeight * 0.04556650246305419;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.042666666666666665,
                        y: constraints.maxHeight * 0.9421182266009852,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup16Widget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.104;

                  final double height =
                      constraints.maxHeight * 0.0480295566502463;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8533333333333334,
                        y: constraints.maxHeight * 0.9445812807881774,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup17Widget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 99.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 43.0,
                child: GeneratedGroup18Widget4(),
              ),
              Positioned(
                left: 65.0,
                top: 676.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 123.0,
                child: GeneratedRectangle55Widget(),
              ),
              Positioned(
                left: 65.0,
                top: 676.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 123.0,
                child: GeneratedRectangle56Widget(),
              ),
              Positioned(
                left: 115.0,
                top: 361.0,
                right: null,
                bottom: null,
                width: 168.0,
                height: 92.0,
                child: Generated52Widget(),
              ),
              Positioned(
                left: 62.0,
                top: 470.0,
                right: null,
                bottom: null,
                width: 296.0,
                height: 47.0,
                child: GeneratedGroup48Widget1(),
              ),
              Positioned(
                left: 113.0,
                top: 586.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 63.0,
                child: GeneratedSTOPWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4198331298828125;

                  final double height =
                      constraints.maxHeight * 0.18114388752453434;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.688,
                        y: constraints.maxHeight * 0.38803912383582206,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup50Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 33.0,
                top: 471.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 44.0,
                child: GeneratedEstimatedTimetoFullChrageWidget1(),
              ),
              Positioned(
                left: 197.0,
                top: 758.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 51.0,
                child: GeneratedGroup64Widget(),
              )
            ]),
      ),
    ));
  }
}
