import 'package:flutter/material.dart';
import 'package:flutterapp/ev_chargapp/generatedhistorywidget/generated/GeneratedFasolidhistoryWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedhistorywidget/generated/GeneratedGroup51Widget5.dart';
import 'package:flutterapp/ev_chargapp/generatedhistorywidget/generated/GeneratedEllipse12Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/ev_chargapp/generatedhistorywidget/generated/GeneratedNotificationWidget1.dart';
import 'package:flutterapp/ev_chargapp/generatedhistorywidget/generated/GeneratedGroup22Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedhistorywidget/generated/GeneratedBibatterychargingWidget1.dart';
import 'package:flutterapp/ev_chargapp/generatedhistorywidget/generated/GeneratedGroup17Widget1.dart';
import 'package:flutterapp/ev_chargapp/generatedhistorywidget/generated/GeneratedRectangle43Widget1.dart';
import 'package:flutterapp/ev_chargapp/generatedhistorywidget/generated/GeneratedGroup16Widget1.dart';
import 'package:flutterapp/ev_chargapp/generatedhistorywidget/generated/GeneratedGroup18Widget1.dart';
import 'package:flutterapp/ev_chargapp/generatedhistorywidget/generated/GeneratedGroup67Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedhistorywidget/generated/GeneratedGroup43Widget2.dart';
import 'package:flutterapp/ev_chargapp/generatedhistorywidget/generated/GeneratedShapeWidget1.dart';
import 'package:flutterapp/ev_chargapp/generatedhistorywidget/generated/GeneratedHistoryWidget1.dart';

/* Frame History
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHistoryWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 246, 246, 246),
                ),
              ),
              Positioned(
                left: 349.6666564941406,
                top: 0.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedBibatterychargingWidget1(),
              ),
              Positioned(
                left: -99.0,
                top: -109.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 270.0,
                child: GeneratedShapeWidget1(),
              ),
              Positioned(
                left: 25.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 324.6666564941406,
                height: 16.0,
                child: GeneratedNotificationWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 177.0,
                right: null,
                bottom: null,
                width: 338.0,
                height: 559.0,
                child: GeneratedGroup51Widget5(),
              ),
              Positioned(
                left: 128.0,
                top: 138.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 33.0,
                child: GeneratedHistoryWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 755.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 83.0,
                child: GeneratedRectangle43Widget1(),
              ),
              Positioned(
                left: 259.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 94.0,
                child: GeneratedEllipse12Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.096;

                  final double height =
                      constraints.maxHeight * 0.04556650246305419;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.042666666666666665,
                        y: constraints.maxHeight * 0.9421182266009852,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup16Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.104;

                  final double height =
                      constraints.maxHeight * 0.0480295566502463;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8533333333333334,
                        y: constraints.maxHeight * 0.9445812807881774,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup17Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 99.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 43.0,
                child: GeneratedGroup18Widget1(),
              ),
              Positioned(
                left: -33.0,
                top: 296.0,
                right: null,
                bottom: null,
                width: 407.0001525878906,
                height: 366.0,
                child: GeneratedGroup22Widget(),
              ),
              Positioned(
                left: 131.0,
                top: 186.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 92.0,
                child: GeneratedFasolidhistoryWidget(),
              ),
              Positioned(
                left: 117.0,
                top: 689.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 57.0,
                child: GeneratedGroup43Widget2(),
              ),
              Positioned(
                left: 200.0,
                top: 758.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 51.0,
                child: GeneratedGroup67Widget(),
              )
            ]),
      ),
    ));
  }
}
