import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget/generated/GeneratedNotificationWidget5.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget/generated/GeneratedRectangle57Widget10.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget/generated/GeneratedSTARTWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget/generated/GeneratedGroup63Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget/generated/GeneratedInputWidget14.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget/generated/GeneratedGroup47Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget/generated/GeneratedGroup48Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget/generated/GeneratedGroup16Widget3.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget/generated/GeneratedRectangle43Widget3.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget/generated/GeneratedEstimatedTimetoFullChrageWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget/generated/GeneratedShapeWidget5.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget/generated/GeneratedGroup17Widget3.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget/generated/GeneratedGroup46Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget/generated/GeneratedEllipse12Widget3.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget/generated/GeneratedBibatteryhalfWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedchargingentrywidget/generated/GeneratedGroup18Widget3.dart';

/* Frame Charging Entry
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChargingEntryWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 246, 246, 246),
                ),
              ),
              Positioned(
                left: -99.0,
                top: -109.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 270.0,
                child: GeneratedShapeWidget5(),
              ),
              Positioned(
                left: 25.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 324.6666564941406,
                height: 16.0,
                child: GeneratedNotificationWidget5(),
              ),
              Positioned(
                left: 16.0,
                top: 184.0,
                right: null,
                bottom: null,
                width: 338.0,
                height: 559.0,
                child: GeneratedInputWidget14(),
              ),
              Positioned(
                left: 0.0,
                top: 755.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 83.0,
                child: GeneratedRectangle43Widget3(),
              ),
              Positioned(
                left: 259.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 94.0,
                child: GeneratedEllipse12Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.096;

                  final double height =
                      constraints.maxHeight * 0.04556650246305419;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.042666666666666665,
                        y: constraints.maxHeight * 0.9421182266009852,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup16Widget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.104;

                  final double height =
                      constraints.maxHeight * 0.0480295566502463;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8533333333333334,
                        y: constraints.maxHeight * 0.9445812807881774,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup17Widget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 104.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 43.0,
                child: GeneratedGroup18Widget3(),
              ),
              Positioned(
                left: 266.9970703125,
                top: 321.40289306640625,
                right: null,
                bottom: null,
                width: 177.0,
                height: 159.39466857910156,
                child: GeneratedBibatteryhalfWidget(),
              ),
              Positioned(
                left: 39.0,
                top: 373.0,
                right: null,
                bottom: null,
                width: 292.0,
                height: 48.0,
                child: GeneratedGroup46Widget(),
              ),
              Positioned(
                left: 41.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 316.0,
                height: 60.0,
                child: GeneratedGroup47Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 453.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 23.0,
                child: GeneratedEstimatedTimetoFullChrageWidget(),
              ),
              Positioned(
                left: -33.0,
                top: 492.0,
                right: null,
                bottom: null,
                width: 296.0,
                height: 47.0,
                child: GeneratedGroup48Widget(),
              ),
              Positioned(
                left: 66.0,
                top: 676.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 123.0,
                child: GeneratedRectangle57Widget10(),
              ),
              Positioned(
                left: 105.0,
                top: 586.0,
                right: null,
                bottom: null,
                width: 174.0,
                height: 63.0,
                child: GeneratedSTARTWidget(),
              ),
              Positioned(
                left: 208.0,
                top: 758.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 51.0,
                child: GeneratedGroup63Widget(),
              )
            ]),
      ),
    ));
  }
}
