import 'package:flutter/material.dart';
import 'package:flutterapp/ev_chargapp/generatedprofilewidget/generated/GeneratedMrsSavinduKoshithaWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedprofilewidget/generated/GeneratedInputWidget4.dart';
import 'package:flutterapp/ev_chargapp/generatedprofilewidget/generated/GeneratedLastnameWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedprofilewidget/generated/GeneratedMyProfileWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedprofilewidget/generated/GeneratedInputWidget3.dart';
import 'package:flutterapp/ev_chargapp/generatedprofilewidget/generated/GeneratedInputWidget7.dart';
import 'package:flutterapp/ev_chargapp/generatedprofilewidget/generated/GeneratedGroup34Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedprofilewidget/generated/GeneratedUpdateWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedprofilewidget/generated/GeneratedEllipse11Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedprofilewidget/generated/GeneratedRectangle24Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedprofilewidget/generated/GeneratedAddressWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedprofilewidget/generated/GeneratedMobileNoWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedprofilewidget/generated/GeneratedFirstnameWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedprofilewidget/generated/GeneratedNotificationWidget2.dart';
import 'package:flutterapp/ev_chargapp/generatedprofilewidget/generated/GeneratedInputWidget5.dart';
import 'package:flutterapp/ev_chargapp/generatedprofilewidget/generated/GeneratedRectangle35Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedprofilewidget/generated/GeneratedShapeWidget2.dart';
import 'package:flutterapp/ev_chargapp/generatedprofilewidget/generated/GeneratedInputWidget6.dart';
import 'package:flutterapp/ev_chargapp/generatedprofilewidget/generated/GeneratedNICWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedprofilewidget/generated/GeneratedInputWidget8.dart';

/* Frame Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 246, 246, 246),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 257.0,
                child: GeneratedRectangle24Widget(),
              ),
              Positioned(
                left: -99.0,
                top: -109.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 270.0,
                child: GeneratedShapeWidget2(),
              ),
              Positioned(
                left: 25.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 324.6666564941406,
                height: 16.0,
                child: GeneratedNotificationWidget2(),
              ),
              Positioned(
                left: 137.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedEllipse11Widget(),
              ),
              Positioned(
                left: 137.0,
                top: 81.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 23.0,
                child: GeneratedMyProfileWidget(),
              ),
              Positioned(
                left: 147.0,
                top: 231.0,
                right: null,
                bottom: null,
                width: 221.0,
                height: 23.0,
                child: GeneratedMrsSavinduKoshithaWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 278.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 434.0,
                child: GeneratedInputWidget3(),
              ),
              Positioned(
                left: 70.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 37.0,
                child: GeneratedInputWidget4(),
              ),
              Positioned(
                left: 70.0,
                top: 403.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 37.0,
                child: GeneratedInputWidget5(),
              ),
              Positioned(
                left: 70.0,
                top: 471.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 37.0,
                child: GeneratedInputWidget6(),
              ),
              Positioned(
                left: 70.0,
                top: 553.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 37.0,
                child: GeneratedInputWidget7(),
              ),
              Positioned(
                left: 71.0,
                top: 630.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 37.0,
                child: GeneratedInputWidget8(),
              ),
              Positioned(
                left: 32.0,
                top: 304.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 18.0,
                child: GeneratedFirstnameWidget(),
              ),
              Positioned(
                left: 33.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 18.0,
                child: GeneratedLastnameWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 452.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 18.0,
                child: GeneratedNICWidget(),
              ),
              Positioned(
                left: 33.0,
                top: 602.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 18.0,
                child: GeneratedMobileNoWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 528.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 18.0,
                child: GeneratedAddressWidget(),
              ),
              Positioned(
                left: 33.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 131.0,
                height: 38.0,
                child: GeneratedRectangle35Widget(),
              ),
              Positioned(
                left: 217.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 38.0,
                child: GeneratedGroup34Widget(),
              ),
              Positioned(
                left: 60.0,
                top: 738.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 27.0,
                child: GeneratedUpdateWidget(),
              )
            ]),
      ),
    ));
  }
}
