import 'package:flutter/material.dart';
import 'package:flutterapp/ev_chargapp/generatedreciptwidget/generated/GeneratedWalletBalanceWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/ev_chargapp/generatedreciptwidget/generated/GeneratedKwhWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedreciptwidget/generated/GeneratedAmountWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedreciptwidget/generated/GeneratedShapeWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedreciptwidget/generated/GeneratedGroup51Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedreciptwidget/generated/GeneratedGroup56Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedreciptwidget/generated/GeneratedReceiptWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedreciptwidget/generated/GeneratedRectangle43Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedreciptwidget/generated/GeneratedGroup62Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedreciptwidget/generated/GeneratedGroup18Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedreciptwidget/generated/GeneratedHoursWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedreciptwidget/generated/GeneratedEllipse12Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedreciptwidget/generated/GeneratedGroup17Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedreciptwidget/generated/GeneratedBibatterychargingWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedreciptwidget/generated/GeneratedGroup57Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedreciptwidget/generated/GeneratedGroup43Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedreciptwidget/generated/GeneratedGroup66Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedreciptwidget/generated/GeneratedNotificationWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedreciptwidget/generated/GeneratedGroup58Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedreciptwidget/generated/GeneratedGroup59Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedreciptwidget/generated/GeneratedGroup16Widget.dart';

/* Frame Recipt
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedReciptWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 246, 246, 246),
                ),
              ),
              Positioned(
                left: 349.6666564941406,
                top: 0.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedBibatterychargingWidget(),
              ),
              Positioned(
                left: -99.0,
                top: -109.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 270.0,
                child: GeneratedShapeWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 324.6666564941406,
                height: 16.0,
                child: GeneratedNotificationWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 178.0,
                right: null,
                bottom: null,
                width: 338.0,
                height: 559.0,
                child: GeneratedGroup51Widget(),
              ),
              Positioned(
                left: 128.0,
                top: 139.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 33.0,
                child: GeneratedReceiptWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 755.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 83.0,
                child: GeneratedRectangle43Widget(),
              ),
              Positioned(
                left: 259.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 94.0,
                child: GeneratedEllipse12Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.096;

                  final double height =
                      constraints.maxHeight * 0.04556650246305419;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.042666666666666665,
                        y: constraints.maxHeight * 0.9421182266009852,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup16Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.104;

                  final double height =
                      constraints.maxHeight * 0.0480295566502463;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8533333333333334,
                        y: constraints.maxHeight * 0.9445812807881774,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup17Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 99.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 43.0,
                child: GeneratedGroup18Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 661.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 57.0,
                child: GeneratedGroup43Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 339.0,
                right: null,
                bottom: null,
                width: 323.0,
                height: 23.0,
                child: GeneratedHoursWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 323.0,
                height: 23.0,
                child: GeneratedKwhWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 26.0,
                child: GeneratedAmountWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 562.0,
                right: null,
                bottom: null,
                width: 323.0,
                height: 23.0,
                child: GeneratedWalletBalanceWidget(),
              ),
              Positioned(
                left: 154.0,
                top: 333.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 34.0,
                child: GeneratedGroup56Widget(),
              ),
              Positioned(
                left: 154.0,
                top: 408.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 34.0,
                child: GeneratedGroup57Widget(),
              ),
              Positioned(
                left: 154.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 34.0,
                child: GeneratedGroup58Widget(),
              ),
              Positioned(
                left: 201.0,
                top: 556.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 34.0,
                child: GeneratedGroup59Widget(),
              ),
              Positioned(
                left: 132.0,
                top: 182.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 107.0,
                child: GeneratedGroup62Widget(),
              ),
              Positioned(
                left: 200.0,
                top: 758.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 51.0,
                child: GeneratedGroup66Widget(),
              )
            ]),
      ),
    ));
  }
}
