import 'package:flutter/material.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/GeneratedSavinduKoshithaWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/GeneratedAccountBalanceWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/GeneratedRectangle54Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/GeneratedGroup64Widget1.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/GeneratedGroup16Widget5.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/GeneratedTopupWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/GeneratedNotificationWidget7.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/GeneratedAccountNumberWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/GeneratedWelcomeWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/GeneratedChargeWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/Generated841133556Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/Generated25011LKRWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/GeneratedRectangle53Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/GeneratedHistoryWidget2.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/GeneratedInputWidget16.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/GeneratedIonexitWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/GeneratedRectangle43Widget5.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/GeneratedEllipse12Widget5.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/GeneratedGroup17Widget5.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/GeneratedExitWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/GeneratedShapeWidget7.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/GeneratedGroup44Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/GeneratedGroup45Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/GeneratedFasolidhistoryWidget1.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/GeneratedRectangle55Widget1.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/GeneratedRectangle56Widget1.dart';
import 'package:flutterapp/ev_chargapp/generatedhome_page1widget/generated/GeneratedGroup18Widget5.dart';

/* Frame Home_Page1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHome_Page1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 107, 29, 29),
                ),
              ),
              Positioned(
                left: -99.0,
                top: -109.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 270.0,
                child: GeneratedShapeWidget7(),
              ),
              Positioned(
                //Time wedght
                left: 25.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 324.6666564941406,
                height: 16.0,
                child: GeneratedNotificationWidget7(),
              ),
              Positioned(
                //welcome note
                left: 150.0,
                top: 124.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 23.0,
                child: GeneratedWelcomeWidget(),
              ),
              Positioned(
                //Transparent white background
                left: 20.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 559.0,
                child: GeneratedInputWidget16(),
              ),
              Positioned(
                //Home top Bar
                left: 0.0,
                top: 760.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 83.0,
                child: GeneratedRectangle43Widget5(),
              ),
              Positioned(
                left: 259.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 94.0,
                child: GeneratedEllipse12Widget5(), //home profile picture
              ),
              Positioned(
                //Home icon in the bottom bar
                left: 10.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.096;

                  final double height =
                      constraints.maxHeight * 0.04556650246305419;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.042666666666666665,
                        y: constraints.maxHeight * 0.9421182266009852,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup16Widget5(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                //Setting bar
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.104;

                  final double height =
                      constraints.maxHeight * 0.0480295566502463;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8533333333333334,
                        y: constraints.maxHeight * 0.9445812807881774,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup17Widget5(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 120.0,
                top: 795.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 43.0,
                child: GeneratedGroup18Widget5(), //Map icon
              ),
              Positioned(
                left: 80.0,
                top: 186.0,
                right: null,
                bottom: null,
                width: 263.0,
                height: 37.0,
                child: GeneratedSavinduKoshithaWidget(), //person name home
              ),
              Positioned(
                left: 120.0,
                top: 235.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 23.0,
                child:
                    GeneratedAccountBalanceWidget(), //Account Balance homepage
              ),
              Positioned(
                left: 45.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 183.0,
                height: 23.0,
                child:
                    GeneratedAccountNumberWidget(), //Account Text wedget in the home
              ),
              Positioned(
                left: 123.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 173.0,
                height: 23.0,
                child: Generated25011LKRWidget(), //Acc Balance
              ),
              Positioned(
                left: 250.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 131.0,
                height: 26.0,
                child: Generated841133556Widget(), //AccNo 841133
              ),
              Positioned(
                left: 35.0,
                top: 536.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 123.0,
                child: GeneratedRectangle53Widget(), //charge white image
              ),
              Positioned(
                left: 214.0,
                top: 536.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 123.0,
                child: GeneratedRectangle54Widget(), //History changes
              ),
              Positioned(
                left: 35.0,
                top: 699.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 123.0,
                child: GeneratedRectangle55Widget1(), //topup icon white
              ),
              Positioned(
                left: 214.0,
                top: 699.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 123.0,
                child: GeneratedRectangle56Widget1(), //Exit icon
              ),
              Positioned(
                //history black icon
                left: 235.0,
                top: 433.0,
                right: null,
                bottom: null,
                width: 88.0,
                height: 83.0,
                child: GeneratedFasolidhistoryWidget1(),
              ),
              Positioned(
                //charge black icon
                left: 40.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 113.0,
                child: GeneratedGroup44Widget(),
              ),
              Positioned(
                //topup icon image
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 35.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.25066666666666665;

                  final double height =
                      constraints.maxHeight * 0.10467980295566502;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.12533333333333332,
                        y: constraints.maxHeight * 0.7327586206896551,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup45Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                //Exit black icon
                left: 240.0,
                top: 591.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 94.0,
                child: GeneratedIonexitWidget(),
              ),
              Positioned(
                //charg lable in the home
                left: 65.0,
                top: 536.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 26.0,
                child: GeneratedChargeWidget(),
              ),
              Positioned(
                //History lable in the home
                left: 250.0,
                top: 540.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 26.0,
                child: GeneratedHistoryWidget2(),
              ),
              Positioned(
                //topup lable in the home
                left: 60.0,
                top: 704.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 26.0,
                child: GeneratedTopupWidget1(),
              ),
              Positioned(
                //Exit lable in the home
                left: 260.0,
                top: 703.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 26.0,
                child: GeneratedExitWidget(),
              ),
              Positioned(
                //news icon in the home bar
                left: 220.0,
                top: 790.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 51.0,
                child: GeneratedGroup64Widget1(),
              )
            ]),
      ),
    ));
  }
}
