import 'package:flutter/material.dart';
import 'package:flutterapp/ev_chargapp/generatedcomplete_crgwidget/generated/GeneratedShapeWidget4.dart';
import 'package:flutterapp/ev_chargapp/generatedcomplete_crgwidget/generated/GeneratedChrgingCompleteWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedcomplete_crgwidget/generated/GeneratedGroup17Widget2.dart';
import 'package:flutterapp/ev_chargapp/generatedcomplete_crgwidget/generated/GeneratedGroup54Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedcomplete_crgwidget/generated/GeneratedAmountWidget1.dart';
import 'package:flutterapp/ev_chargapp/generatedcomplete_crgwidget/generated/GeneratedNotificationWidget4.dart';
import 'package:flutterapp/ev_chargapp/generatedcomplete_crgwidget/generated/GeneratedGroup16Widget2.dart';
import 'package:flutterapp/ev_chargapp/generatedcomplete_crgwidget/generated/GeneratedGroup51Widget6.dart';
import 'package:flutterapp/ev_chargapp/generatedcomplete_crgwidget/generated/GeneratedBibatteryfullWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedcomplete_crgwidget/generated/GeneratedGroup53Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/ev_chargapp/generatedcomplete_crgwidget/generated/GeneratedGroup65Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedcomplete_crgwidget/generated/GeneratedEllipse12Widget2.dart';
import 'package:flutterapp/ev_chargapp/generatedcomplete_crgwidget/generated/GeneratedRectangle43Widget2.dart';
import 'package:flutterapp/ev_chargapp/generatedcomplete_crgwidget/generated/GeneratedBibatterychargingWidget2.dart';
import 'package:flutterapp/ev_chargapp/generatedcomplete_crgwidget/generated/GeneratedTotalConsumptionpowercapacityWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedcomplete_crgwidget/generated/GeneratedGroup55Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedcomplete_crgwidget/generated/GeneratedGroup43Widget3.dart';
import 'package:flutterapp/ev_chargapp/generatedcomplete_crgwidget/generated/Generated100Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedcomplete_crgwidget/generated/GeneratedGroup18Widget2.dart';

/* Frame Complete_Crg
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedComplete_CrgWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 246, 246, 246),
                ),
              ),
              Positioned(
                left: 349.6666564941406,
                top: 0.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedBibatterychargingWidget2(),
              ),
              Positioned(
                left: -99.0,
                top: -109.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 270.0,
                child: GeneratedShapeWidget4(),
              ),
              Positioned(
                left: 25.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 324.6666564941406,
                height: 16.0,
                child: GeneratedNotificationWidget4(),
              ),
              Positioned(
                left: 14.0,
                top: 178.0,
                right: null,
                bottom: null,
                width: 338.0,
                height: 559.0,
                child: GeneratedGroup51Widget6(),
              ),
              Positioned(
                left: 52.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 30.0,
                child: GeneratedChrgingCompleteWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 755.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 83.0,
                child: GeneratedRectangle43Widget2(),
              ),
              Positioned(
                left: 259.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 94.0,
                child: GeneratedEllipse12Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.096;

                  final double height =
                      constraints.maxHeight * 0.04556650246305419;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.042666666666666665,
                        y: constraints.maxHeight * 0.9421182266009852,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup16Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.104;

                  final double height =
                      constraints.maxHeight * 0.0480295566502463;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8533333333333334,
                        y: constraints.maxHeight * 0.9445812807881774,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup17Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 99.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 43.0,
                child: GeneratedGroup18Widget2(),
              ),
              Positioned(
                left: 98.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 205.0,
                height: 92.0,
                child: Generated100Widget(),
              ),
              Positioned(
                left: 249.005859375,
                top: 166.00439453125,
                right: null,
                bottom: null,
                width: 150.09239196777344,
                height: 136.99868774414062,
                child: GeneratedBibatteryfullWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 323.0,
                height: 44.0,
                child: GeneratedTotalConsumptionpowercapacityWidget(),
              ),
              Positioned(
                left: 35.0,
                top: 601.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 23.0,
                child: GeneratedAmountWidget1(),
              ),
              Positioned(
                left: 25.0,
                top: 465.0,
                right: null,
                bottom: null,
                width: 294.1840515136719,
                height: 47.0,
                child: GeneratedGroup55Widget(),
              ),
              Positioned(
                left: 149.0,
                top: 585.0,
                right: null,
                bottom: null,
                width: 160.18405151367188,
                height: 60.0,
                child: GeneratedGroup54Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 525.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 47.0,
                child: GeneratedGroup53Widget(),
              ),
              Positioned(
                left: 120.0,
                top: 660.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 57.0,
                child: GeneratedGroup43Widget3(),
              ),
              Positioned(
                left: 201.0,
                top: 758.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 51.0,
                child: GeneratedGroup65Widget(),
              )
            ]),
      ),
    ));
  }
}
