import 'package:flutter/material.dart';
import 'package:flutterapp/ev_chargapp/generatedtopupwidget/generated/GeneratedRectangle24Widget1.dart';
import 'package:flutterapp/ev_chargapp/generatedtopupwidget/generated/GeneratedRectangle35Widget1.dart';
import 'package:flutterapp/ev_chargapp/generatedtopupwidget/generated/GeneratedFullNameWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedtopupwidget/generated/GeneratedShapeWidget3.dart';
import 'package:flutterapp/ev_chargapp/generatedtopupwidget/generated/GeneratedNotificationWidget3.dart';
import 'package:flutterapp/ev_chargapp/generatedtopupwidget/generated/GeneratedInputWidget12.dart';
import 'package:flutterapp/ev_chargapp/generatedtopupwidget/generated/GeneratedAccountNoWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedtopupwidget/generated/GeneratedRectangle59Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedtopupwidget/generated/GeneratedInputWidget9.dart';
import 'package:flutterapp/ev_chargapp/generatedtopupwidget/generated/GeneratedRectangle60Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedtopupwidget/generated/GeneratedMrsSavinduKoshithaWidget1.dart';
import 'package:flutterapp/ev_chargapp/generatedtopupwidget/generated/GeneratedAccountbalanceWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedtopupwidget/generated/GeneratedInputWidget11.dart';
import 'package:flutterapp/ev_chargapp/generatedtopupwidget/generated/GeneratedRectangle58Widget.dart';
import 'package:flutterapp/ev_chargapp/generatedtopupwidget/generated/GeneratedInputWidget10.dart';
import 'package:flutterapp/ev_chargapp/generatedtopupwidget/generated/GeneratedTopUPWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedtopupwidget/generated/GeneratedSelectPaymentMethodsWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedtopupwidget/generated/GeneratedOkWidget.dart';
import 'package:flutterapp/ev_chargapp/generatedtopupwidget/generated/GeneratedEllipse11Widget1.dart';
import 'package:flutterapp/ev_chargapp/generatedtopupwidget/generated/GeneratedRectangle61Widget.dart';

/* Frame Topup
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTopupWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            clipBehavior: Clip.none,
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 79, 16, 16),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 257.0,
                child: GeneratedRectangle24Widget1(),
              ),
              Positioned(
                left: -99.0,
                top: -109.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 270.0,
                child: GeneratedShapeWidget3(),
              ),
              Positioned(
                left: 25.0,
                top: 5.0,
                right: null,
                bottom: null,
                width: 324.6666564941406,
                height: 16.0,
                child: GeneratedNotificationWidget3(),
              ),
              Positioned(
                left: 137.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedEllipse11Widget1(), //topup page profile picture
              ),
              Positioned(
                left: 157.0,
                top: 80.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 26.0,
                child: GeneratedTopUPWidget(),
              ),
              Positioned(
                left: 147.0,
                top: 231.0,
                right: null,
                bottom: null,
                width: 221.0,
                height: 23.0,
                child: GeneratedMrsSavinduKoshithaWidget1(),
              ),
              Positioned(
                left: 14.0,
                top: 273.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 434.0,
                child: GeneratedInputWidget9(),
              ),
              Positioned(
                left: 123.0,
                top: 298.0,
                right: null,
                bottom: null,
                width: 223.0,
                height: 35.0,
                child: GeneratedInputWidget10(),
              ),
              Positioned(
                left: 122.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 223.0,
                height: 37.0,
                child: GeneratedInputWidget11(),
              ),
              Positioned(
                left: 168.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 177.0,
                height: 37.0,
                child: GeneratedInputWidget12(),
              ),
              Positioned(
                left: 21.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 18.0,
                child: GeneratedFullNameWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 18.0,
                child: GeneratedAccountNoWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 416.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 18.0,
                child: GeneratedAccountbalanceWidget(),
              ),
              Positioned(
                left: 84.0,
                top: 472.0,
                right: null,
                bottom: null,
                width: 221.0,
                height: 21.0,
                child: GeneratedSelectPaymentMethodsWidget(),
              ),
              Positioned(
                left: 121.0,
                top: 737.0,
                right: null,
                bottom: null,
                width: 131.0,
                height: 38.0,
                child: GeneratedRectangle35Widget1(),
              ),
              Positioned(
                left: 174.0,
                top: 745.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 27.0,
                child: GeneratedOkWidget(),
              ),
              Positioned(
                left: 44.0,
                top: 540.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 49.0,
                child: GeneratedRectangle58Widget(),
              ),
              Positioned(
                left: 194.0,
                top: 540.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 49.0,
                child: GeneratedRectangle59Widget(),
              ),
              Positioned(
                left: 194.0,
                top: 619.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 49.0,
                child: GeneratedRectangle60Widget(),
              ),
              Positioned(
                left: 44.0,
                top: 619.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 49.0,
                child: GeneratedRectangle61Widget(),
              )
            ]),
      ),
    ));
  }
}
